function problem(res) {
  if (res.status === 401) return '⚠️ TeamContext: TEAM_TOKEN rejected by the server. Tell the user to fix the MCP config.';
  const reason = res.error ?? `HTTP ${res.status}`;
  return res.status === 0
    ? `⚠️ TeamContext server unreachable (${reason}). Coordination is OFFLINE: tell the user before editing shared files.`
    : `⚠️ TeamContext request failed (${reason}). Coordination is OFFLINE: tell the user before editing shared files.`
}

export function lockMessage(res, filePath) {
  if (res.status === 200) return `✅ Lock granted for ${filePath}`;
  if (res.status === 409) {
    return `⚠️ CONFLICT: ${res.data.conflict_with} has been editing ${filePath} since ${res.data.acquired_at}. Do not edit this file.`;
  }
  return problem(res);
}

export function unlockMessage(res, filePath) {
  if (res.status === 200) return `🔓 Lock released for ${filePath}`;
  if (res.status === 404) return `⚠️ No active lock found for ${filePath}`;
  return problem(res);
}

export function releaseAllMessage(res) {
  return res.status === 200 ? `🔓 Released ${res.data.count} locks` : problem(res);
}

export function teamStatusMessage(statusRes, activityRes, me) {
  if (!statusRes.ok) return problem(statusRes);
  const locks = statusRes.data.active_locks;
  const lines = [`TeamContext status (you are "${me}")`, ''];

  lines.push(locks.length ? `Active locks (${locks.length}):` : 'Active locks: none — all clear.');
  for (const l of locks) {
    lines.push(`- ${l.file_path} — ${l.developer_id === me ? 'YOU' : l.developer_id} since ${l.acquired_at}`);
  }

  const events = activityRes.ok ? activityRes.data.events : [];
  if (!activityRes.ok) lines.push('', problem(activityRes));
  if (events.length) {
    lines.push('', 'Recent activity (newest first):');
    for (const e of events) {
      const file = e.file_path ? ` ${e.file_path}` : '';
      const note = e.summary ? ` — "${e.summary}"` : '';
      lines.push(`- [${e.created_at}] ${e.developer_id} ${e.event}${file}${note}`);
    }
  }
  return lines.join('\n');
}
