import { test } from 'node:test';
import assert from 'node:assert/strict';
import { lockMessage, unlockMessage, releaseAllMessage, teamStatusMessage } from '../lib/messages.js';

const down = { ok: false, status: 0, error: 'timeout after 10000ms' };

test('lock granted', () =>
  assert.equal(lockMessage({ ok: true, status: 200, data: {} }, 'src/a.js'), '✅ Lock granted for src/a.js'));

test('lock conflict tells Bob not to edit', () =>
  assert.equal(
    lockMessage({ ok: false, status: 409, data: { conflict_with: 'bob', acquired_at: '2026-09-26T10:00:00.000Z' } }, 'src/a.js'),
    '⚠️ CONFLICT: bob has been editing src/a.js since 2026-09-26T10:00:00.000Z. Do not edit this file.',
  ));

test('server down is a warning, not a crash', () =>
  assert.match(lockMessage(down, 'src/a.js'), /^⚠️ TeamContext server unreachable \(timeout after 10000ms\)/));

test('bad token is explicit', () =>
  assert.match(lockMessage({ ok: false, status: 401, data: {} }, 'src/a.js'), /TEAM_TOKEN rejected/));

test('unlock', () => {
  assert.equal(unlockMessage({ ok: true, status: 200, data: {} }, 'src/a.js'), '🔓 Lock released for src/a.js');
  assert.equal(unlockMessage({ ok: false, status: 404, data: {} }, 'src/a.js'), '⚠️ No active lock found for src/a.js');
});

test('release all', () =>
  assert.equal(releaseAllMessage({ ok: true, status: 200, data: { count: 3 } }), '🔓 Released 3 locks'));

test('team status lists locks and activity, marking your own', () => {
  const status = { ok: true, status: 200, data: { active_locks: [
    { developer_id: 'alice', file_path: 'src/a.js', acquired_at: 'T1' },
    { developer_id: 'bob', file_path: 'src/b.js', acquired_at: 'T2' },
  ] } };
  const activity = { ok: true, status: 200, data: { events: [
    { developer_id: 'bob', event: 'unlock', file_path: 'src/c.js', summary: 'Fixed footer', created_at: 'T0' },
  ] } };
  const text = teamStatusMessage(status, activity, 'alice');
  assert.match(text, /- src\/a\.js — YOU since T1/);
  assert.match(text, /- src\/b\.js — bob since T2/);
  assert.match(text, /bob unlock src\/c\.js — "Fixed footer"/);
});

test('team status when nobody is working', () =>
  assert.match(
    teamStatusMessage({ ok: true, status: 200, data: { active_locks: [] } }, { ok: true, status: 200, data: { events: [] } }, 'alice'),
    /Active locks: none — all clear\./,
  ));
